config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '/',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 sign_up: 'register'
             },
             controllers: {
                 registrations: 'registrations',
                 passwords: 'passwords',
                 sessions: 'sessions'
             }

  namespace :api do
    namespace :v1 do
      resources :labels, only: [:update]

      resources :snippets, except: [:show] do
        member do
          get 'raw', to: 'snippets#raw', as: 'raw_snippet'
        end
      end

      get 'data/default-state', to: 'data#default_state'
      get 'data/update-state', to: 'data#update_state'
    end
  end

  get 'help', to: 'pages#help'

  root 'repository#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/editor.rb
class Editor
  def self.languages
    data = YAML.load_file(File.join(Rails.root, 'config', 'editor.yml'))
    data['languages'].symbolize_keys
  end
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :snippets

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :label, optional: true

  counter_culture :label

  accepts_nested_attributes_for :label

  validates :title, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 20000 }
  validates :language, presence: true, inclusion: { in: Editor.languages.keys.map(&:to_s) }
  validates :tabs, numericality: { only_integer: true }, inclusion: { in: [2, 4, 8] }

  after_commit :remove_unused_labels

  private

  def remove_unused_labels
    Label.where('snippets_count < 1').destroy_all
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/data_controller.rb
class Api::V1::DataController < Api::BaseController
  def default_state
    data = {
      snippets: ActiveModelSerializers::SerializableResource.new(Snippet.all, each_serializer: ::SnippetSerializer),
      languages: Editor.languages
    }
    render json: data
  end
end

app/controllers/api/v1/labels_controller.rb
class Api::V1::LabelsController < Api::BaseController
  include ResponseData

  before_action :set_label, only: [:update]

  def update
    completed = @label.update(label_params)
    render json: entity_save_data(@label, completed)
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/controllers/api/v1/snippets_controller.rb
class Api::V1::SnippetsController < Api::BaseController
  include ResponseData

  before_action :set_snippet, except: :create

  def create
    @snippet = Snippet.new(snippet_params)
    completed = @snippet.save
    render json: entity_save_data(@snippet, completed)
  end

  def update
    completed = @snippet.update(snippet_params)
    render json: entity_save_data(@snippet, completed)
  end

  def destroy
    @snippet.destroy
    data = { completed: true }
    render json: data
  end

  def raw
    render plain: @snippet.content
  end

  private

  def set_snippet
    @snippet = Snippet.find(params[:id])
  end

  def snippet_params
    # TODO: it's legacy for core counter_cache issues
    data = params.require(:snippet).permit(:title, :content, :language, :tabs, label_attributes: [:name])
    label = data[:label_attributes]['name'].blank? ? nil : Label.find_or_create_by(name: data[:label_attributes]['name'])
    data.except(:label_attributes).merge(label: label)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_properties

  def set_properties
    @activate_repository = false
    @body_class = "default"
    @page_title = ""
  end
end

app/controllers/concerns/response_data.rb
module ResponseData
  extend ActiveSupport::Concern

  def entity_save_data(entity, completed)
    if completed
      { completed: true, entity: "#{entity.class}Serializer".constantize.new(entity).attributes }
    else
      { completed: false, errors: entity.errors.full_messages }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
    @page_title = "Help"
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  before_action :credentials_locked?, only: [:new, :update], if: -> { ENV['DEMO'].present? }

  private
  def credentials_locked?
    redirect_to new_user_session_path, notice: "Reset password disabled on demo version."
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]
  before_action :credentials_locked?, only: [:update, :destroy], if: -> { ENV['DEMO'].present? }

  def edit
    @page_title = 'Settings'
    super
  end

  protected

  def one_user_registered?
    if User.count == 1
      redirect_to root_path if user_signed_in?
      redirect_to new_user_session_path, notice: 'Snibox allow registration just for one user.'
    end
  end

  def credentials_locked?
    redirect_back(fallback_location: root_path, notice: 'Credentials locked for demo version. You can change them on your setup.')
  end
end

app/controllers/repository_controller.rb
class RepositoryController < ApplicationController
  def index
    @activate_repository = true
    @body_class = "dashboard"
    @page_title = "Dashboard"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  before_action :lock_credentials, only: :new, if: -> { ENV['DEMO'].present? }

  private

  def lock_credentials
    flash[:success] = <<-HTML
        <p>Email: #{ENV['DEMO_EMAIL']}</p>
        <p>Password: #{ENV['DEMO_PASSWORD']}</p>
    HTML
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_notifications
    notifications = []
    flash.each do |key, value|
      css_class = case key
                  when 'alert'
                    'is-danger'
                  when 'notice'
                    'is-warning'
                  when 'error'
                    'is-danger'
                  when 'success'
                    'is-success'
                  else
                    'is-info'
                  end
      notifications << content_tag(:div, value.html_safe, class: "notification #{css_class}")
    end
    notifications.join('').html_safe
  end

  def render_auth_errors
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)
    html = <<-HTML
    <div class="notification is-danger">     
      <p>#{sentence}</p>
      <ul>#{messages}</ul>
    </div>
    HTML
    html.html_safe
  end

  def is_active_page(path)
    current_page?(path) ? "is-active" : ""
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Snibox | <%= @page_title.empty? ? yield(:page_title) : @page_title %></title>

  <%= render 'shared/apple_touch_icons' %>

  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_pack_path('images/favicon.ico') %>

  <%= stylesheet_pack_tag 'common' %>
  <%= render 'shared/rspec_disable_animations' if Rails.env.test? %>
</head>

<body class="<%= @body_class %>">
<%= render 'shared/navbar' %>

<%= yield %>

<!-- js -->
<%= javascript_pack_tag 'vendor' %>
<%= javascript_pack_tag 'common' %>
<%= @activate_repository ? javascript_pack_tag('repository') : javascript_pack_tag('page') %>
<%= javascript_pack_tag 'navbar' %>

</body>
</html>

app/views/pages/help.html.erb
<section class="section">
  <div id="page-wrapper" class="animated fadeInUp">
    <div class="container">

      <div class="columns">
        <div class="column is-6-widescreen is-offset-3-widescreen is-10-desktop is-offset-1-desktop">
          <div class="card">
            <div class="card-header">
              <div class="card-header-title">Local storage</div>
            </div>
            <div class="card-content">
              <button class="button is-primary" @click="resetLocalStorage()">Reset local storage</button>
            </div>
          </div>
        </div>
      </div>

      <div class="columns">
        <div class="column is-6-widescreen is-offset-3-widescreen is-10-desktop is-offset-1-desktop">
          <div class="card">
            <div class="card-header">
              <div class="card-header-title">Source code</div>
            </div>
            <div class="card-content">
              <%= link_to "https://github.com/snibox/snibox", "https://github.com/snibox/snibox", target: "_blank" %>
            </div>
          </div>
        </div>
      </div>

      <div class="columns">
        <div class="column is-6-widescreen is-offset-3-widescreen is-10-desktop is-offset-1-desktop">
          <div class="card">
            <div class="card-header">
              <div class="card-header-title">Documentation</div>
            </div>
            <div class="card-content">
              <%= link_to "https://snibox.github.io/docs", "https://snibox.github.io/docs/", target: "_blank" %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/repository/index.html.erb
<div id="app"></div>

app/views/shared/_apple_touch_icons.html.erb
<!-- apple touch icons -->
<%= tag("link", rel: "apple-touch-icon", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "57x57", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-57x57.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "72x72", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-72x72.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "76x76", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-76x76.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "114x114", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-114x114.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "120x120", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-120x120.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "144x144", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-144x144.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "152x152", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-152x152.png')) %>
<%= tag("link", rel: "apple-touch-icon", sizes: "180x180", href: asset_pack_path('images/apple-touch-icons/apple-touch-icon-180x180.png')) %>

app/views/shared/_auth_form.html.erb
<section class="section">
  <div id="page-wrapper" class="animated fadeInUp">
    <div class="container">
      <div class="columns">
        <div class="column is-6-widescreen is-offset-3-widescreen is-10-desktop is-offset-1-desktop">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title"><%= title %></p>
            </header>

            <div class="card-content">
              <%= render_notifications if !flash.empty? %>
              <div class="content">
                <%= yield %>
              </div>
            </div>

            <% unless user_signed_in? %>
              <footer class="card-footer">
                <%= render "devise/shared/links" %>
              </footer>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar animated slideInDown">
  <div class="container is-fluid">
    <div class="navbar-brand">
      <%= link_to root_path, class: 'navbar-item' do %>
        <img id="logo" :src="logo" alt="Snibox"/>
      <% end %>
      <search-box class="navbar-item is-hidden-desktop"></search-box>
      <% if user_signed_in? %>
        <div class="navbar-burger burger" data-target="navbar-menu">
          <span></span>
          <span></span>
          <span></span>
        </div>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <div id="navbar-menu" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Dashboard", root_path, id: "dashboard", class: "navbar-item #{is_active_page(root_path)}" %>
          <a id="snippet-new" class="navbar-item" href="#" @click="addSnippet($event, <%= !current_page?(root_path) %>)">
            Add snippet
          </a>
        </div>
        <div class="navbar-end">
          <search-box class="navbar-item is-hidden-mobile is-hidden-tablet-only"></search-box>
          <%= link_to "Help", help_path, id: "help", class: "navbar-item #{is_active_page(help_path)}" %>
          <%= link_to "Settings", edit_user_registration_path, id: "settings", class: "navbar-item #{is_active_page(edit_user_registration_path)}" %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, id: :logout, class: "navbar-item") %>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_rspec_disable_animations.html.erb
<style>
  * {
    transition-property: none !important;
    -o-transition-property: none !important;
    -moz-transition-property: none !important;
    -ms-transition-property: none !important;
    -webkit-transition-property: none !important;

    transform: none !important;
    -o-transform: none !important;
    -moz-transform: none !important;
    -ms-transform: none !important;
    -webkit-transform: none !important;

    animation: none !important;
    -o-animation: none !important;
    -moz-animation: none !important;
    -ms-animation: none !important;
    -webkit-animation: none !important;
  }
</style>